registrationapp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

from studentreg import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("studentreg.urls")),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="studentreg/login.html"),
        name="login",
    ),
    path(
        "logout",
        auth_views.LogoutView.as_view(template_name="studentreg/logout.html"),
        name="logout",
    ),
    path("profile", views.profile, name="profile"),
   
    path(
        "password_reset/",
        views.CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        views.CustomPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        views.CustomPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        views.CustomPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentreg/urls.py
from django.urls import path, include
from . import views
from rest_framework.routers import DefaultRouter
from .views import ModuleListView, StudentViewSet, RegistrationCreateView

router = DefaultRouter()
router.register(r'students', StudentViewSet)


app_name = "studentreg"

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("contact/", views.contact, name="contact"),
    path("course/", views.courses, name="courses"),
    path("course/<int:id>", views.course_detail, name="course_detail"),
    path("module/<str:code>", views.module_detail, name="module_detail"),
    path("module_register/<str:code>", views.module_register, name="module_register"),
    path(
        "module_unregister/<str:code>",
        views.module_unregister,
        name="module_unregister",
    ),
    path("my-registration/", views.my_registrations, name="my_registrations"),
    path("module/<str:code>/submit-feedback/", views.module_feedback, name="module_feedback"),
    path('api/modules/', ModuleListView.as_view(), name='module-list'),
    path('api/registrations/create/', RegistrationCreateView.as_view(), name='registration-create'),
    path('api/', include(router.urls)),

]

studentreg/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group

from .models import Student, ModuleFeedback

# Form for new user registration
class RegisterForm(UserCreationForm):
    """Form definition for user/student registration."""

    username = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "inputField",
                "id": "Username",
            }
        ),
    )

    first_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "First Name",
                "class": "inputField",
                "id": "First Name",
            }
        ),
    )

    last_name = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Last Name",
                "class": "inputField",
                "id": "Last Name",
            }
        ),
    )
    email = forms.CharField(
        max_length=30,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Email",
                "class": "inputField",
                "id": "Email",
            }
        ),
    )

    password1 = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "inputField",
                "id": "Password",
            }
        ),
    )

    password2 = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Confirm Password",
                "class": "inputField",
                "id": "Password2",
            }
        ),
    )

    class Meta:
        """Meta definition for Registerform."""

        model = User
        fields = [
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        ]


class StudentCreationForm(forms.ModelForm):
    """Form definition for Student."""

    course = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        empty_label="Select Course",
        widget=forms.Select(
            attrs={
                "placeholder": "courses",
                "class": "inputField",
                "id": "Courses",
            }
        ),
    )

    gender = forms.ChoiceField(
        choices=(
            ("male", "Male"),
            ("female", "Female"),
            ("other", "Other"),
        ),
        widget=forms.Select(
            attrs={
                "id": "gender",
                "class": "inputField",
                "placeholder": "gender",
            }
        ),
    )

    class Meta:
        """Meta definition for Studentform."""

        model = Student
        fields = ("course", "gender")


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]


class StudentProfileUpdateForm(forms.ModelForm):
    gender = forms.ChoiceField(
        choices=(
            ("male", "Male"),
            ("female", "Female"),
            ("other", "Other"),
        )
    )

    class Meta:
        """Meta definition for Studentform."""

        model = Student
        fields = (
            "date_of_birth",
            "gender",
            "address",
            "city",
            "country",
            "gender",
            "photo",
        )

        widgets = {
            "date_of_birth": forms.DateInput(
                attrs={
                    "id": "date_of_birth",
                    "placeholder": "DD-MM-YYYY",
                    "type": "date",
                }
            ),
            "address": forms.TextInput(
                attrs={
                    "id": "address",
                }
            ),
            "city": forms.TextInput(
                attrs={
                    "id": "city",
                }
            ),
            "country": forms.TextInput(
                attrs={
                    "id": "country",
                }
            ),
            "photo": forms.FileInput(
                attrs={
                    "id": "photo",
                }
            ),
        }
# Form for feedback from students
class ModuleFeedbackForm(forms.ModelForm):
    class Meta:
        model = ModuleFeedback
        fields = ['feedback_text', 'rating']

studentreg/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from rest_framework import generics, viewsets
from .serializers import ModuleSerializer, StudentSerializer, RegistrationSerializer
import requests


from .utils import send_mail,get_educational_quote

# Importing all forms
from .forms import (
    RegisterForm,
    UserUpdateForm,
    StudentProfileUpdateForm,
    StudentCreationForm,
    ModuleFeedbackForm,
)

# Password reset
from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from .models import Student, Module, Group, Registration, ModuleFeedback

def home(request):
        # To retrieve all courses
    courses = Group.objects.all()
    quotes = get_educational_quote()
    context = {"title": "Welcome", "courses": courses, "quotes": quotes}
    return render(request, "studentreg/home.html", context)


def about(request):
    return render(request, "studentreg/about.html", {"title": "About"})


def contact(request):
    return render(request, "studentreg/contact.html", {"title": "Contact"})


def courses(request):
    courses = Group.objects.all()
    return render(request, "studentreg/courses.html", {"title": "Courses","courses": courses })

# Register authentication
def register(request):
   # Initialize forms

    student_form = StudentCreationForm()
    register_form = RegisterForm()

    if request.method == "POST":
       # Get data from forms
        register_form = RegisterForm(request.POST)
        student_form = StudentCreationForm(request.POST)

        if register_form.is_valid() and student_form.is_valid():
         # To Create user and student objects
            user = register_form.save(commit=False)
            course = student_form.cleaned_data.get("course")
            gender = student_form.cleaned_data.get("gender")
            student = Student(user=user, course=course, gender=gender)
            user.save()
            student.save()
            messages.success(
                request, f"Your account has been created! Now you can login!"
            )
            return redirect("login")
        else:
            messages.warning(request, f"Unable to create account!") 

    context = {
        "title": "Register",
        "student_form": student_form,
        "register_form": register_form,
    }
    return render(request, "studentreg/register.html", context)

# To update profile (user has to be logged in)
@login_required
def profile(request):
    if request.method == "POST":
        # Get form data and update user and student profiles
        u_form = UserUpdateForm(request.POST, instance=request.user)
        sp_form = StudentProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.student
        )
        if u_form.is_valid and sp_form.is_valid:
            u_form.save()
            sp_form.save()
            send_mail(email=request.user.email, subject="Profile Updated",message="Your account has been successfully updated")
            messages.success(request, "Your account has been successfully updated")
            return redirect("profile")
    else:
        # Forms with existing user and student data
        u_form = UserUpdateForm(instance=request.user)
        sp_form = StudentProfileUpdateForm(instance=request.user.student)
    context = {"u_form": u_form, "sp_form": sp_form, "title": "Student Profile"}
    return render(request, "studentreg/profile.html", context)


def course_detail(request, id):
    # Get course details and modules associated with a course
    course = get_object_or_404(Group, id=id)
    context = {"title": "Modules", "course": course, "modules": course.modules.all()}
    return render(request, "studentreg/course_detail.html", context)


def module_detail(request, code):
    student = None
    if request.user.is_authenticated and not request.user.is_staff:
        student = request.user.student

    # Get module details and related registrations
    module = get_object_or_404(Module, code=code)
    feedback = module.modulefeedback_set.all()  # Retrieve all feedback for the module

    context = {
        "title": "Modules",
        "registrations": module.module_registrations, 
        "module": module,
        "feedback": feedback
        }
    if student:
        context["has_registered"]=student.registered_on_module(module)
        
    return render(request, "studentreg/module_detail.html", context)

# To register on a module (You have to be logged in)
@login_required
def module_register(request, code):
    
    # Get module and student details
    module = get_object_or_404(Module, code=code)
    student = request.user.student  # to fetch current logged in student

    if Registration.objects.filter(student=student, module=module).exists():
        messages.warning(request, "You are already registered for this module.")
    else:
        
        # Create a new registration
        Registration.objects.create(student=student, module=module)
        messages.success(
            request, f"You have successfully registered for {module.name}."
        )
    return redirect("studentreg:module_detail", code=code)


@login_required
def module_unregister(request, code):
    
    # Get module and student details
    module = get_object_or_404(Module, code=code)
    student = request.user.student  # to fetch current logged in student
    try:
        
        # Delete existing registration
        registration = Registration.objects.get(student=student, module=module)
        registration.delete()
    except Registration.DoesNotExist:
        messages.warning(request, "You are not registered on this module.")
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def my_registrations(request):
    
    # Get student's registrations and paginate them
    student = request.user.student  
    registrations = student.student_registrations.select_related('module').order_by('-date_of_registration')

    # Paginate the registrations
    paginator = Paginator(registrations, 3)  # Show 3 registrations per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'studentreg/my_registrations.html', {'page_obj': page_obj})


class CustomPasswordResetView(PasswordResetView):
    # i think  django will not find the user by the incorrect email
    # so no email will get sent

    # Custom Password Reset View
    email_template_name = "auth/password_reset_email.html"
    subject_template_name = "auth/password_reset_subject.txt"
    template_name = "auth/password_reset_form.html"

    def get_success_url(self):
        return reverse("password_reset_done")


class CustomPasswordResetDoneView(PasswordResetDoneView):
    # Custom Password Reset Done View
    template_name = "auth/password_reset_done.html"


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    # Custom Password Reset Confirm View
    template_name = "auth/password_reset_confirm.html"

    # redirect to login page after successful password reset
    # we also need to show errors if user puts unmatching passwords
    def get_success_url(self):
        return reverse("login")


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    
    # Custom Password Reset Complete View
    template_name = "auth/password_reset_complete.html"

@login_required
def module_feedback(request, code):
    module = get_object_or_404(Module, code=code)
    student = request.user.student

    if request.method == 'POST':
        form = ModuleFeedbackForm(request.POST)
        if form.is_valid():
            feedback = form.save(commit=False)
            feedback.module = module
            feedback.student = student
            feedback.save()
            messages.success(request, 'Feedback submitted successfully!')
            return redirect('studentreg:module_detail', code=code)
    else:
        form = ModuleFeedbackForm()

    context = {'form': form, 'module': module}
    return render(request, 'studentreg/module_feedback.html', context)


class ModuleListView(generics.ListAPIView):
    queryset = Module.objects.all()
    serializer_class = ModuleSerializer

class StudentViewSet(viewsets.ModelViewSet):
    queryset = Student.objects.all()
    serializer_class = StudentSerializer

class RegistrationCreateView(generics.CreateAPIView):
    serializer_class = RegistrationSerializer


# def get_educational_quote(api_token):
#     url = "https://quotes.rest/qod?category=students"
#     headers = {"Authorization": f"Bearer {api_token}"}

#     response = requests.get(url, headers=headers)
#     if response.status_code == 200:
#         data = response.json()
#         if "contents" in data and "quotes" in data["contents"]:
#             quote = data["contents"]["quotes"][0]["quote"]
#             return quote
#     return None

# api_token = "YluVtr6xRlWf0e6viTLeNjs7YQQU2ykRjL5zfVA4r"
# quote = get_educational_quote(api_token)
# print(quote)

# def get_educational_quote(request):
#     url = "https://quotes.rest/qod?category=students"
#     response = requests.get(url)
#     if response.status_code == 200:
#         data = response.json()
#         if "contents" in data and "quotes" in data["contents"]:
#             quotes = data["contents"]["quotes"]
#             return render(request, 'quotes/quotes.html', {'quotes': quotes})
#     return render(request, 'quotes/quotes.html', {'error': 'Failed to fetch quotes'})

studentreg/templates/studentreg/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Student IT Services - {{title}}</title>

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
      rel="stylesheet"
    />

    <!-- Vendor CSS Files -->
    <link
      href="{% static 'assets/vendor/animate.css/animate.min.css' %}"
      rel="stylesheet"
    />
    <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet" />
    <link
      href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}"
      rel="stylesheet"
    />
    <link
      href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}"
      rel="stylesheet"
    />

    <link
      href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}"
      rel="stylesheet"
    />
    <link
      href=" {%  static 'assets/vendor/remixicon/remixicon.css' %}"
      rel="stylesheet"
    />
    <link
      href=" {%  static 'assets/vendor/swiper/swiper-bundle.min.css' %}"
      rel="stylesheet"
    />

    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet" />
    <title>Student Registration Portal - {{title}}</title>
  </head>

  <body>
    <header id="header" class="fixed-top">
      <div class="container-fluid d-flex align-items-center">
        <h1 class="logo me-auto">
          <a href="{% url 'studentreg:home' %}">Techie</a>
        </h1>

        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <li>
              <a href="{% url 'studentreg:home' %}">Home</a>
            </li>
            <li><a href="{% url 'studentreg:about' %}">About</a></li>
            <li><a href="{% url 'studentreg:contact' %}">Contact</a></li>
            <li><a href="{% url 'studentreg:courses'%}">Courses</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'profile' %}">Profile</a></li>
            <li>
              <a href="{% url 'studentreg:my_registrations' %}"
                >My Registrations</a
              >
            </li>
            {% endif %}
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>
        <!-- .navbar -->

        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="get-started-btn">Log out</a>
        {% else %}
        <a href="{% url 'login' %}" class="get-started-btn">Log in</a>
        <a href="{% url 'register' %}" class="get-started-btn">Register</a>
        {% endif %}
      </div>
    </header>

    {% if messages %} {% for message in messages %}
    <div class="alert alert-{{message.tags}}">{{ message }}</div>
    {% endfor %} {% endif %}
    <div style="margin-top: 50px">{% block content %}{% endblock %}</div>
    <footer id="footer">
      <div class="footer-top">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-6 footer-contact">
              <h2>Techie</h2>
              <p>
                Computing Dept <br />
                Sheffield, S1 1WB <br />
                United Kingdom <br /><br />
                <strong>Phone:</strong> +44 1234 567 890<br />
                <strong>Email:</strong> techie@uk.com<br />
              </p>
            </div>
            <div class="col-lg-2 col-md-6 footer-links">
              <h4>Useful links</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Home</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">About Us</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Courses</a>
                </li>

                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Terms of service</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Privacy policy</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-3 col-md-6 footer-links">
              <h4>Courses</h4>
              <ul>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Artificial Intelligence</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Big Data Analytics</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Computer Games Technology</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i> <a href="#">Computing</a>
                </li>
                <li>
                  <i class="bx bx-chevron-right"></i>
                  <a href="#">Cyber Security</a>
                </li>
              </ul>
            </div>

            <div class="col-lg-4 col-md-6 footer-newsletter">
              <h4>Join Our Newsletter</h4>
              <p>Be the first to know about our new courses and discounts!</p>
              <form action="" method="post">
                <input type="email" name="email" /><input
                  type="submit"
                  value="Subscribe"
                />
              </form>
            </div>
          </div>
        </div>
      </div>

      <div class="container d-md-flex py-4">
        <div class="me-md-auto text-center text-md-start">
          <div class="copyright">
            &copy; Copyright <strong><span>Techie</span></strong
            >. All Rights Reserved
          </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
          <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
          <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
          <a href="#" class="instagram"><i class="bx bxl-instagram-alt"></i></a>
          <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
      </div>
    </footer>

    <!-- <div id="preloader"></div>
      <a
        href="#"
        class="back-to-top d-flex align-items-center justify-content-center"
        ><i class="bi bi-arrow-up-short"></i
      ></a>
    </div> -->

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/animate.css/animate.min.css' %}"></script>
    <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>
  </body>
</html>

studentreg/templates/studentreg/courses.html
{% extends "studentreg/base.html" %} {% load static %} {% block content %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs" data-aos="fade-in">
    <div class="container">
      <h2>Our Courses</h2>
      <p>
        Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia
        id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam
        aperiam consequatur laboriosam nemo harum praesentium.
      </p>
    </div>
  </div>
<section id="courses" class="modules">
  <div class="container" data-aos="fade-up">
    <div class="section-title">
    </div>

    <div class="row mb" data-aos="zoom-in" data-aos-delay="100">
      {% for course in courses %}
      <div class="col-lg-3 col-md-6 d-flex align-items-stretch">
        <div class="course-item">
          <img
            src="{% static 'assets/img/AI.jpg' %}"
            class="img-fluid"
            alt="..."
          />
          <div class="course-content">
            <div
              class="d-flex justify-content-between align-items-center mb-3"
            >
              <h4>
                <a href="{% url 'studentreg:course_detail' course.id %}"
                  >{{course.name}}</a
                >
              </h4>
            </div>
            <p>
              Study of building intelligent systems that can perceive, reason,
              learn, and interact with their environment autonomously.
            </p>
          </div>
        </div>
      </div>
      {% endfor %}
   <!-- End Course Item-->
  </div>
</section>
</main>
{% endblock %}

studentreg/templates/studentreg/logout.html
{% extends "studentreg/base.html" %} {% block content %}

<h3 class="lgout pad">You have now been logged out</h3>

<div class="border-top pt-3">
  <small class="text-muted pb-2"
    ><a href="{% url 'login' %}" class="get-started-btn ">Log in</a>

</div>
{% endblock content %}

studentreg/templates/studentreg/module_detail.html
{% extends "studentreg/base.html" %} {% load static %} {% block content %}

<main class="container-fluid">
  <section class="container">
    <h1 class="color">Module Details:</h1>

    <h6 class="card-title">
      <a href="{% url 'studentreg:module_detail' module.code%}"></a>
      <strong>{{module.name}}</strong>
    </h6>
    <p class="card-text">{{module.code}}</p>
    <p class="card-text"><strong>Credit:</strong> {{module.category}}</p>
    <p class="card-text">
      <strong>Availability:</strong>{% if module.availability %} Open {% else %}
      Closed {% endif %}
    </p>

    <div class="reg">
      {% if has_registered %}
      <a
        href="{% url 'studentreg:module_unregister' module.code %}"
        class="regBtn"
        >Unregister
      </a>
      <a
        href="{% url 'studentreg:module_feedback' module.code %}"
        class="regBtn"
        >Feedback
      </a>
      {% else %}
      <a
        href="{% url 'studentreg:module_register' module.code %}"
        class="regBtn"
        >Register
      </a>

      {% endif %}
    </div>
    <h1 class="color mt-4">Registrations</h1>
    {% if user.is_authenticated %} {%for registration in registrations %}
    <li class="list-group-item list-group-item-light">
      <img
        class="rounded-circle article-img"
        src="{{registration.student.photo.url}}"
      />

      <span class="article-content"
        >{{registration.student.user.first_name}}
        {{registration.student.user.last_name}}
      </span>
    </li>
    {% empty %}
    <p>No student registered</p>
    {% endfor%} {%endif%}

    <h3 class="color mt-4">Feedback for {{ module.name }}</h3>
    <table class="table table-striped mb">
      <thead>
        <tr>
          <th>Feedback</th>
          <th>Rating</th>
          <th>Date</th>
        </tr>
      </thead>
      {% for fb in feedback %}
      <tbody
      <tr>
        <td>{{ fb.feedback_text }}</td>
        <td>{{ fb.rating }}/5</td>
        <td>{{ fb.date_submitted }}</td>
      </tr>
    {% empty %}
    <p>No feedback yet.</p>
    {% endfor %}
    </tbody>
  </table>

  </section>
</main>

{% endblock %}

studentreg/templates/studentreg/module_feedback.html
{% extends "studentreg/base.html" %} {% load static %} {% block content %}
<div class="pad">
  <h2 class="color">Submit Feedback for {{ module.name }}</h2>
  <form method="post">
    {% csrf_token %} {{ form.as_p }}
    <button class="regBtn mb-4" type="submit">Submit Feedback</button>
  </form>
</div>
{% endblock %}

studentreg/templates/studentreg/my_registrations.html
{% extends "studentreg/base.html" %} {% load static %} {% block content %}
<div class="container">
  <h2 class="pad color">My Registrations</h2>
  <table class="table table-hover table-striped mb">
    <thead>
      <tr>
        <th>Module Name</th>
        <th>Date of Registration</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for registration in page_obj %}
      <tr>
        <td>{{ registration.module.name }}</td>
        <td>{{ registration.date_of_registration }}</td>
        <td>
          <a
            href="{% url 'studentreg:module_unregister' registration.module.code %}"
            class="btn btn-danger"
            >Unregister
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <div class="pagination mb">
    <span class="step-links">
      {% if page_obj.has_previous %}
      <a href="?page=1" class="nextBtn">&laquo; first</a>
      <a href="?page={{ page_obj.previous_page_number }}" class="nextBtn"
        >previous</a
      >
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }} " class="nextBtn">Next</a>
      <a href="?page={{ page_obj.paginator.num_pages }} " class="nextBtn"
        >Last &raquo;</a
      >
      {% endif %}
    </span>
  </div>
</div>
{% endblock %}

studentreg/templates/studentreg/password.reset.complete.html
{% extends "studentreg/base.html" %} {% load static %} {% block content %}
<h2 class="color">Password Reset Complete!</h2>
<p>Your password has been successfully reset.</p>
{% endblock %}

studentreg/templates/studentreg/profile.html
{% extends "studentreg/base.html" %} {% load static %}{% load crispy_forms_tags
  %} {% block content %}
  
  <div class="profile">
    <div class="media mb">
      <img class="rounded-circle account-img" src="{{user.student.photo.url}}" />
  
      <div class="media-body">
        <h2 class="account-heading color">{{user.username}}</h2>
        <p class="text-secondary">{{user.email}}</p>
      </div>
    </div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
  
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Profile Details</legend>
  
        {{ u_form.as_p }} {{ sp_form.as_p }}
      </fieldset>
      <button type="Update" class="mb regBtn">Update</button>
    </form>
  </div>
  {% endblock content %}